### PR TITLE
Quote structs and decoding

### PR DESCRIPTION
**Pull request by elichai**
Structs for the quote in `isv_enclave_quote` and functions to decode and parse it into attributes.

Will add functions for quote verification.

### CODE REVIEW

**Comment by elichai** [comment]
This will require installing these packages in the dockers `pkg-config, libssl-dev` because of using bindings to openssl: https://crates.io/crates/openssl

**Comment by Isan-Rivkin** [comment]
utACK, should be merged as soon as it's added to the docker (pkg-config, libssl-dev) network IMO (@lacabra)

**Comment by lacabra** [comment]
@elichai, @Isan-Rivkin I confirm that core's docker base image `baiduxlab/sgx-rust:1.0.0` already includes these two packages in the following versions:
* `pkg-config`: 0.29.1 (latest)
* `libssl-dev`:  1.0.2g-1ubuntu4.12 (upgradable to 1.0.2g-1ubuntu4.13)

Thus, I think that both existing versions should be fine (let me know otherwise), and this can be merged.

**Comment by elichai** [comment]
@lacabra you're right. I will check the parent dockerfile next time :)

**Comment by lacabra** [comment]
@elichai alternatively I boot the core container and list the installed packages to check what package versions if any it already has.

**Pull request merged**
